apiVersion: v1
kind: ServiceAccount
metadata:
  name: test
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::739561048503:role/eks-prod-ssm-pm-role
---
apiVersion: v1
kind: Pod
metadata:
  name: aws-param-test
spec:
  serviceAccountName: test
  containers:
    - name: param-test
      image: 739561048503.dkr.ecr.us-east-1.amazonaws.com/aws-parameter-init-container:latest
      imagePullPolicy: Always
      environment:
        - name: PARAMETERS
          value: "roboshop.prod.rabbitmq.amqp_user roboshop.prod.rabbitmq.amqp_pass"

