apiVersion: v1
kind: Pod
metadata:
  name: aws-param-test
spec:
  containers:
    - name: param-test
      image: 739561048503.dkr.ecr.us-east-1.amazonaws.com/aws-parameter-init-container:latest
      imagePullPolicy: Always
